name: infra
description: A TypeScript program to deploy a Kubernetes cluster on Azure
runtime:
  name: nodejs
  options:
    packagemanager: npm
config:
  pulumi:tags:
    value:
      pulumi:template: kubernetes-azure-typescript
